import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";
import Constants from "expo-constants";


type userData = {
  name?: string;
  email: string;
  password?: string;
  passwordConfirm?: string;
  otp?: string;
};

export const authApi = createApi({
  reducerPath: "authApi",
  baseQuery: fetchBaseQuery({
    baseUrl: `${Constants.expoConfig?.extra?.EXPO_BACKEND_URL}api/v1/auth`,
  }),
  endpoints: (builder) => ({
    signUpUser: builder.mutation({
      query: (userData: userData) => ({
        url: "/signup",
        method: "POST",
        body: userData,
      }),
    }),

    loginUser: builder.mutation({
      query: (userData: userData) => ({
        url: "/login",
        method: "POST",
        body: userData,
      }),
    }),

    tokenStatus: builder.query({
      query: (token: string) => {
        console.log("checking token status");
        return {
          url: "/token-status",
          headers: {
            Authorization: `Bearer ${token}`,
          },
        };
      },
    }),

    forgotPassword: builder.mutation({
      query: (email: string) => ({
        url: "/forgot-password",
        method: "POST",
        body: { email },
      }),
    }),

    OtpVerify: builder.mutation({
      query: (userData: userData) => {
        return {
          url: "/check-otp",
          method: "POST",
          body: userData,
        };
      },
    }),

    resetPassword: builder.mutation({
      query: (userData: userData) => {
        return {
          url: "/reset-password",
          method: "PATCH",
          body: userData,
        };
      },
    }),

    checkAvailability: builder.mutation({
      query: ({ username, email }: { username: string; email: string }) => ({
        url: "/check-availability",
        method: "POST",
        body: { username, email },
      }),
    }),
  }),
});

// ⬇️ Export hooks generated by the API
export const {
  useSignUpUserMutation,
  useLoginUserMutation,
  useTokenStatusQuery,
  useForgotPasswordMutation,
  useOtpVerifyMutation,
  useResetPasswordMutation,
  useCheckAvailabilityMutation,
} = authApi;
